### ISSUE TITLE
Multiphase (soil-water) with DesignSPHysics

### ISSUE THREAD

**Issue by Falko90** [zlotny/DesignSPHysics#25]
Hello, is there a possibility to set up a multiphase case (soil-water) with DesignSPHysics and FreeCAD, respectively? I didn't find the necessary settings there (especially to enable additional parameters like the Herschel-Bulkley-Papanastasiou model)  and could only set up a simulation using the XML-files directly as shown in the case. 
I hope it's okay that I posed my question here and not in the official DualSPHysics forum.
Thank you very much in advance!

**Comment by zlotny** [comment]
Hi there!

Right now, DesignSPHysics does not support the multiphase version of the code, so for now, thats a no to your question.

You can, though, design the case entirely in FreeCAD, save it, and then adapt the XML to the multiphase version of DualSPHysics.

Multiphase will be implemented in the future. Sorry about that :(
